name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: UdayVaidya
          template: classic
          base: header, activity, community
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_colors: github
          plugin_stars: yes
          plugin_commits: yes
